name: poker-chip
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - fenics-dolfinx>=0.8.0
  - mpi4py
  - petsc4py
  - python-gmsh
  - pip
  - pip:
      - numpy>=1.21
      - scipy>=1.7
      - pyyaml>=5.4
      - omegaconf>=2.3
      - matplotlib>=3.5
      - scienceplots>=2.0
      - scifem>=0.16.1
      - hydra-core>=1.3
      - hydra-joblib-launcher>=1.2
      - hydra-submitit-launcher>=1.2