name: poker-chip
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.13
  - fenics-dolfinx==0.10
  - mpi4py
  - petsc4py
  - python-gmsh
  - scifem
  - matplotlib
  - pytest
  - pytest-mpi
  - jupyterlab
  - scienceplots
  - numpy
  - scipy
  - pyyaml
  - pip
  - pip:
      - scipy>=1.7
      - pyyaml>=5.4
      - omegaconf>=2.3
     # - scifem>=0.16.1
      - hydra-core>=1.3
      - hydra-joblib-launcher>=1.2
      - hydra-submitit-launcher>=1.2