defaults:
  - config
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: gpu
    timeout_min: 60
    cpus_per_task: 1
    gpus_per_node: 0
    tasks_per_node: 1
    mem_gb: 4
    nodes: 1
    name: ${hydra.job.name}