defaults:
  - _self_
  - parameters_linear

hydra:
  run:
    # Simplified output directory with key parameters
    dir: results/${output_name}/L${geometry.L}_H${geometry.H}_hdiv${geometry.h_div}/${now:%Y%m%d_%H%M%S}
  sweep:
    # Clean multirun directory structure
    dir: results/${output_name}/multirun_${now:%Y%m%d_%H%M%S}
    subdir: L${geometry.L}_H${geometry.H}_hdiv${geometry.h_div}_${geometry.geometric_dimension}D
  job:
    chdir: true
    config:
      override_dirname:
        kv_sep: '='
        item_sep: '_'
        exclude_keys:
          - output_name
          - now