model:
  mu: 0.59
  kappa: 500.0

geometry:
  geometric_dimension: 2
  L: 1.0
  H: 0.1
  h_div: 3.0

fem:
  degree_u: 1
  stabilization_gamma: 0.1

output_name: "poker_linear"
load_max: 0.1
sliding: 1

solvers:
  elasticity:
    snes:
      snes_type: newtonls
      snes_rtol: 1.0e-8
      snes_atol: 1.0e-8
      snes_max_it: 25
      ksp_type: preonly
      pc_type: lu
    prefix: "elasticity_"