model:
  mu: 1.0
  kappa: 500.0

geometry:
  geometric_dimension: 2
  L: 10.0
  H: 1.0
  h_div: 5.0

fem:
  element: "CR"
  degree_u: 1

output_name: "poker_linear"
load_max: 1.0
sliding: 0

solvers:
  elasticity:
    snes:
      snes_type: ksponly
      snes_rtol: 1.0e-8
      snes_atol: 1.0e-8
      snes_max_it: 25
      ksp_type: preonly
      pc_type: lu
    prefix: "elasticity_"